# Generated by Django 5.1.4 on 2025-01-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
